/**
 * Created by tygiacalone on 4/22/16.
 */

// grab the things we need
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

// create a schema
var restaurantSchema = new Schema({
    name: String,
    username: { type: String, required: true, unique: true },
    tags: [{
        afternoon: {type: Boolean},
        authentic: {type: Boolean},
        authentic_takeout: {type: Boolean},
        baked_goods: {type: Boolean},
        bar_area: {type: Boolean},
        bar_scene: {type: Boolean},
        bar_seating: {type: Boolean},
        beer_and_wine: {type: Boolean},
        beer_selection: {type: Boolean},
        casual: {type: Boolean},
        celeb_spotting: {type: Boolean},
        chef_inventive: {type: Boolean},
        classy: {type: Boolean},
        communal_tables: {type: Boolean},
        date_night: {type: Boolean},
        date_spot: {type: Boolean},
        dietary_restriction_friendly: {type: Boolean},
        dog_friendly: {type: Boolean},
        family_friendly: {type: Boolean},
        famous_chef: {type: Boolean},
        fancy: {type: Boolean},
        farm_to_table: {type: Boolean},
        first_date: {type: Boolean},
        foodie_famous: {type: Boolean},
        fun: {type: Boolean},
        fusion: {type: Boolean},
        gastropub: {type: Boolean},
        GF_options: {type: Boolean},
        good_ambiance: {type: Boolean},
        good_drinks : {type: Boolean},
        good_for_families: {type: Boolean},
        good_for_groups: {type: Boolean},
        good_for_parents: {type: Boolean},
        great_view: {type: Boolean},
        happy_hour: {type: Boolean},
        hard_to_get_a_table: {type: Boolean},
        healthy_options: {type: Boolean},
        hidden_gem: {type: Boolean},
        hotel_dining: {type: Boolean},
        hotspot: {type: Boolean},
        innovative: {type: Boolean},
        karaoke: {type: Boolean},
        lively: {type: Boolean},
        lively_bar_area: {type: Boolean},
        locals: {type: Boolean},
        new_restaurant: {type: Boolean},
        no_reservations: {type: Boolean},
        open_late: {type: Boolean},
        order_at_counter: {type: Boolean},
        organic: {type: Boolean},
        organic_beer_and_wine: {type: Boolean},
        outdoor_dining: {type: Boolean},
        outdoor_seating: {type: Boolean},
        pastries: {type: Boolean},
        prime_location: {type: Boolean},
        private_room: {type: Boolean},
        quiet: {type: Boolean},
        romantic: {type: Boolean},
        rotating_menu: {type: Boolean},
        scenery: {type: Boolean},
        seat_yourself: {type: Boolean},
        secret: {type: Boolean},
        share_plates: {type: Boolean},
        shareable: {type: Boolean},
        small_plates: {type: Boolean},
        snack: {type: Boolean},
        special_occasion: {type: Boolean},
        swanky: {type: Boolean},
        sweet_treat: {type: Boolean},
        take_out_options: {type: Boolean},
        takes_dinner_reservations: {type: Boolean},
        takes_walk_ins: {type: Boolean},
        tasting_menu: {type: Boolean},
        trendy: {type: Boolean},
        upscale: {type: Boolean},
        vegan_options: {type: Boolean},
        vegetarian_options: {type: Boolean},
        wine_bar: {type: Boolean},
        worth_the_lines: {type: Boolean}
    }],
    food_types: [{
        all_american: {type: Boolean},
        asian: {type: Boolean},
        bakery: {type: Boolean},
        british: {type: Boolean},
        chinese: {type: Boolean},
        french: {type: Boolean},
        fusion: {type: Boolean},
        german: {type: Boolean},
        greek: {type: Boolean},
        indian: {type: Boolean},
        italian: {type: Boolean},
        japanese: {type: Boolean},
        korean: {type: Boolean},
        mexican: {type: Boolean},
        middle_eastern: {type: Boolean},
        pizza: {type: Boolean},
        seafood: {type: Boolean},
        seasonal_local: {type: Boolean},
        south_american: {type: Boolean},
        steakhouse: {type: Boolean},
        sushi: {type: Boolean},
        sushi_bar: {type: Boolean},
        tapas: {type: Boolean},
        thai: {type: Boolean},
        vegan: {type: Boolean}
    }],
    meals: [{
        breakfast: {type: Boolean},
        brunch: {type: Boolean},
        lunch: {type: Boolean},
        coffee: {type: Boolean},
        dinner: {type: Boolean},
        drinks: {type: Boolean},
        happy_hour: {type: Boolean}
    }],
    location: String,
    created_at: Date,
    updated_at: Date
});

// the schema is useless so far
// we need to create a model using it
var Restaurant = mongoose.model('Restaurant', restaurantSchema);

// make this available to our users in our Node applications
module.exports = Restaurant;